# --- 外观颜色配置 (Appearance Colors) ---
# 根背景颜色
rootcolor=0x0f141eff
# 默认边框颜色
bordercolor=0x1a1b2eff
# 拖拽目标指示颜色
dropcolor=0x00d4aa55
# 聚焦窗口边框颜色
focuscolor=0x00d4aaff
# 最大化窗口边框颜色
maximizescreencolor=0x00d4aaff
# 紧急提醒窗口边框颜色
urgentcolor=0xf7768eff
# 便签窗口边框颜色
scratchpadcolor=0x00f0d0ff
# 全局窗口边框颜色
globalcolor=0x00d4aaff
# 覆盖层窗口边框颜色
overlaycolor=0x9ece6aff
