# --- 外观颜色配置 (Appearance Colors) ---
# 根背景颜色
rootcolor=0x1a1b26ff
# 默认边框颜色
bordercolor=0x24283bff
# 拖拽目标指示颜色
dropcolor=0x7aa2f755
# 聚焦窗口边框颜色
focuscolor=0xbb9af7ff
# 最大化窗口边框颜色
maximizescreencolor=0xbb9af7ff
# 紧急提醒窗口边框颜色
urgentcolor=0xf7768eff
# 便签窗口边框颜色
scratchpadcolor=0x7dcffff
# 全局窗口边框颜色
globalcolor=0xbb9af7ff
# 覆盖层窗口边框颜色
overlaycolor=0x9ece6aff
