# --- 外观颜色配置 (Appearance Colors) ---
# 根背景颜色
rootcolor=0x1e1e2eff
# 默认边框颜色
bordercolor=0x313244ff
# 拖拽目标指示颜色
dropcolor=0x89b4fa55
# 聚焦窗口边框颜色
focuscolor=0xcba6f7ff
# 最大化窗口边框颜色
maximizescreencolor=0xcba6f7ff
# 紧急提醒窗口边框颜色
urgentcolor=0xf38ba8ff
# 便签窗口边框颜色
scratchpadcolor=0x89dcebff
# 全局窗口边框颜色
globalcolor=0xcba6f7ff
# 覆盖层窗口边框颜色
overlaycolor=0xa6e3a1ff
