# Foot 终端配置
# shell=/bin/bash
term=foot
font=JetBrainsMono Nerd Font:size=11

[scrollback]
lines=10000

[url]
launch=xdg-open ${url}

[cursor]
style=underline
blink=yes

# ------------------------------------------------------------
# 暗黑模式配色 (Tokyo Night Storm)
# ------------------------------------------------------------
[colors-dark]
background=1a1b26
foreground=c0caf5

regular0=15161e  # black
regular1=f7768e  # red
regular2=9ece6a  # green
regular3=e0af68  # yellow
regular4=7aa2f7  # blue
regular5=bb9af7  # magenta
regular6=7dcfff  # cyan
regular7=a9b1d6  # white

bright0=414868   # bright black
bright1=f7768e   # bright red
bright2=9ece6a   # bright green
bright3=e0af68   # bright yellow
bright4=7aa2f7   # bright blue
bright5=bb9af7   # bright magenta
bright6=7dcfff   # bright cyan
bright7=c0caf5   # bright white

# ------------------------------------------------------------
# 亮色模式配色 (Tokyo Night Light)
# ------------------------------------------------------------
[colors-light]
background=d5d6db
foreground=343b58

regular0=1c1e21  # black
regular1=f7768e  # red
regular2=485e30  # green
regular3=896a24  # yellow
regular4=2e7de9  # blue
regular5=9854f1  # magenta
regular6=007197  # cyan
regular7=6172b0  # white

bright0=4d555f   # bright black
bright1=f7768e   # bright red
bright2=485e30   # bright green
bright3=896a24   # bright yellow
bright4=2e7de9   # bright blue
bright5=9854f1   # bright magenta
bright6=007197   # bright cyan
bright7=343b58   # bright white

[csd]
# 禁用 Wayland 装饰，由合成器管理
size=0